<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Robots" nsURI="http://wmp.dsm" nsPrefix="wmp.dsm">
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="x > 0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndIf" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="x"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subprogram" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableInitialization" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="x"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomInitialization" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="x"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotorsForward" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="M3, M4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotorsBackward" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="M3, M4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StopMotors" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Motors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="M1, M2, M3, M4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearEncoder" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="E1, E2, E3, E4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timer" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
</ecore:EPackage>
